version: '3'

services:
  db:
    image: mysql/mysql-server:5.7
    environment:
      - TZ=Europe/Moscow
      - MYSQL_USER=zmuser
      - MYSQL_PASSWORD=zmpass
      - MYSQL_DATABASE=zm
      - MYSQL_ROOT_PASSWORD=mysqlpsswd
      - MYSQL_ROOT_HOST=%
  web:
    image: quantumobject/docker-zoneminder
    volumes:
      - ${PWD}/backups:/var/backups
      - ${PWD}/zoneminder:/var/cache/zoneminder
    environment:
      - TZ=Europe/Moscow
      - VIRTUAL_HOST=zm.localhost, stream.localhost
      - SERVICE_PORTS=${WEB_PORT}
      - ZM_SERVER_HOST=node
      - ZM_DB_HOST=db
    depends_on:
      - db
  stream:
    image: quantumobject/docker-zoneminder
    volumes:
      - ${PWD}/backups:/var/backups
      - ${PWD}/zoneminder:/var/cache/zoneminder
    environment:
      - TZ=Europe/Moscow
      - VIRTUAL_HOST=stream.localhost
      - SERVICE_PORTS=${WEB_PORT}
      - ZM_SERVER_HOST=node
      - ZM_DB_HOST=db
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    depends_on:
      - web