version: '3'

services:
  db:
    image: mysql/mysql-server:5.7
    hostname: db
    networks:
      net:
        aliases:
          - db
    volumes:
      - ${PWD}/mysql:/var/lib/mysql
      - ${PWD}/conf/mysql:/etc/mysql:ro
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - MYSQL_USER=zmuser
      - MYSQL_PASSWORD=zmpass
      - MYSQL_DATABASE=zm
      - MYSQL_ROOT_PASSWORD=mysqlpsswd
      - MYSQL_ROOT_HOST=%
  web:
    image: quantumobject/docker-zoneminder
    networks:
      - net
    volumes:
      - /var/empty
      - ${PWD}/backups:/var/backups
      - ${PWD}/zoneminder:/var/cache/zoneminder
    environment:
      - TZ=Europe/Moscow
      - VIRTUAL_HOST=zm.localhost, stream0.localhost
      - SERVICE_PORTS=${WEB_PORT}
      - ZM_SERVER_HOST=node.0
      - ZM_DB_HOST=db
    depends_on:
      - db
  stream:
    image: quantumobject/docker-zoneminder
    networks:
      - net
    volumes:
      - /var/empty
      - ${PWD}/backups:/var/backups
      - ${PWD}/zoneminder:/var/cache/zoneminder
    environment:
      - TZ=Europe/Moscow
      - VIRTUAL_HOST=stream{{.Task.Slot}}.localhost
      - SERVICE_PORTS=${WEB_PORT}
      - ZM_SERVER_HOST=node.{{.Task.Slot}}
      - ZM_DB_HOST=db
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    depends_on:
      - web
networks:
  net:
    driver: overlay