version: '3'

services:
  db:
    image: mysql/mysql-server:5.7
    environment:
      - TZ=Europe/Moscow
      - MYSQL_USER=zmuser
      - MYSQL_PASSWORD=zmpass
      - MYSQL_DATABASE=zm
      - MYSQL_ROOT_PASSWORD=mysqlpsswd
      - MYSQL_ROOT_HOST=%
  web:
    image: quantumobject/docker-zoneminder
    volumes:
      - ${PWD}/backups:/var/backups
      - ${PWD}/zoneminder:/var/cache/zoneminder
    environment:
      - TZ=Europe/Moscow
      - ZM_DB_HOST=db
    ports:
      - ${WEB_PORT}:80
    depends_on:
      - db