version: '3'

services:
    plex:
        image: plexinc/pms-docker
        restart: always
        environment:
            TZ: GMT+3
            PLEX_GID: 1000
            PLEX_UID: 1000
            ADVERTISE_IP: ${ADVERTISE_IP}
            PLEX_CLAIM: ${CLAIM_TOKEN}
        volumes:
        - /mnt/media/downloads:/data
        - /mnt/storage/plex/database:/config
        - /mnt/storage/plex/transcode:/transcode
        ports:
        - 32400:32400/tcp
        - 3005:3005/tcp
        - 8324:8324/tcp
        - 32469:32469/tcp
        - 1900:1900/udp
        - 32410:32410/udp
        - 32412:32412/udp
        - 32413:32413/udp
        - 32414:32414/udp