version: '3'

services:
    plex:
        image: plexinc/pms-docker
        restart: always
        environment:
            TZ: GMT+3
            PLEX_GID: 1000
            PLEX_UID: 1000
            ADVERTISE_IP: ${ADVERTISE_IP}
            PLEX_CLAIM: ${CLAIM_TOKEN}
        volumes:
        - /mnt/media/downloads:/data
        - /mnt/storage/plex/database:/config
        - /mnt/storage/plex/transcode:/transcode
        network_mode: "host"